version: 0.2
    
phases:
  install:
    runtime-versions:
      python: 3.9 # IT WILL INSTALL PYTHON 3.9 ON THE ENVIRONMENT
    commands:
      - echo === INSTALLING CFN-LINT ===
      - pip install cfn-lint
    
  pre_build: # CHECK IF YOUR ENV HAS ALL TOOLS
    commands:
      - echo ==== CHECK IF PYTHON AND AWSCLI WAS INSTALLED SUCCESSFULLY ====
      - python3 --version
      - aws --version
      - echo === CHECK CFN-LINT ===
      - cfn-lint --version
    
  build: # RUN YOUR CODE
    commands:
      - echo === CHECK FOR SYNTAX ON OUR TEMPLATE ===
      - cfn-lint 1-ec2-user-data.yaml
      - echo === BUILD OUR CFN TEMPLATE ===
      - aws cloudformation package --template-file 1-ec2-user-data.yaml --s3-bucket my-deployed-artifacts-bucket --output-template-file build-artifact-template.yaml

  post_build:
    commands:
      - echo === THIS IS MY POSTBUILD SECTION ===
      - echo build is completed at `date`... # TELL THE USER WHEN THE BUILD IS COMPLETE

artifacts:
  files:
    - build-artifact-template.yaml # THE ONLY ARTFIFCAT WE WILL USE FOR NEXT STAGE
